Controllers/ProjectsController.cs
using Aurigma.StorefrontApi;
using CustomersCanvasSample.Models;
using CustomersCanvasSample.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomersCanvasSample.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectsApiClient _projectsApiClient;
        private readonly CustomersCanvasOptions _options;

        public ProjectsController(
            IProjectsApiClient projectsApiClient,
            IOptions<CustomersCanvasOptions> options)
        {
            _projectsApiClient = projectsApiClient;
            _options = options.Value;
        }

        [HttpPost]
        public async Task<ActionResult> Create([FromBody] ProjectModel model)
        {
            CreateProjectDto project = new CreateProjectDto()
            {
                OwnerId = model.OwnerId,
                OrderId = model.OrderId,
                OrderNumber = EcommerceDataService.OrderIdToNumber(model.OrderId),
                CustomerId = model.UserId,
                CustomerName = EcommerceDataService.CustomerIdToName(model.UserId),
                ProductReference = model.ProductId,
                Items = model.Items.Select(x => new ProjectItemParametersDto()
                {
                    DesignIds = x.StateId.ToList(),
                    Fields = x.Fields,
                    Hidden = x.Hidden,
                }).ToList()
            };
            
            var result = await _projectsApiClient.CreateAsync(_options.StorefrontId, body: project);
            return new OkObjectResult(result);
        }
    }
}

Controllers/StorefrontController.cs
using CustomersCanvasSample.Services;
using CustomersCanvasSampleMVC.Enums;
using CustomersCanvasSampleMVC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomersCanvasSample.Controllers
{
    public class StorefrontController : Controller
    {
        private EcommerceDataService _ecommerceDataService;
        private readonly DataSourceService _dataSourceService;
        private CustomersCanvasOptions _options;

        public StorefrontController(
            EcommerceDataService ecommerceDataService,
            DataSourceService dataSourceService,
            IOptions<CustomersCanvasOptions> options)
        {
            _ecommerceDataService = ecommerceDataService;
            _dataSourceService = dataSourceService;
            _options = options.Value;
        }

        public async Task<IActionResult> Index()
        {
            var connectedProducts = await _ecommerceDataService.GetConnectedProducts();
            var connectedPimProducts = await _ecommerceDataService.GetConnectedPimProducts();

            return View(connectedProducts.Union(connectedPimProducts));
        }

        public IActionResult Edit(string id)
        {
            var product = _ecommerceDataService.GetProductById(id);

            ViewBag.TenantId = _options.TenantId;
            ViewBag.BackOfficeUrl = _options.IdentityProviderUrl;
            ViewBag.EcommerceSystemId = _options.StorefrontId;

            // It is supposed that user is authorised.
            // Otherwise the session should be generated.
            ViewBag.UserId = 1234;

            return product.EditorType switch
            {
                EditorType.UIFramework => View(product),
                EditorType.SimpleEditor => View("SimpleEditor", product),
                _ => throw new NotImplementedException(),
            };
        }

        public IActionResult Personalize(string id, bool LoadDataToTemplate)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.BackOfficeUrl = _options.IdentityProviderUrl;
            ViewBag.LoadDataToTemplate = LoadDataToTemplate;

            // It is supposed that user is authorised.
            // Otherwise the session should be generated.
            ViewBag.UserId = 1234;
            ViewBag.Data = _dataSourceService.GetDataForTemplate();

            return View(_ecommerceDataService.GetProductById(id));
        }
    }
}

Views/Storefront/Edit.cshtml
@model Product
@using System.Globalization;
@*
	Here we display the product page of your online store. As usual, you want to add a "Personalize" button here which should 
	open the design in the editor.
*@
@{
	ViewData["Title"] = Model.Name;
}

<div class="container" id="store-content">
	<div class="row">
		<!-- Left Column -->
		<div class="col">
			<div id="demoCarousel" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					<div class="carousel-item active">
						<img src="@Model.ImageUrl" alt="First slide">
					</div>
					<div class="carousel-item">
						<img src="@Model.ImageUrl" alt="Second slide">
					</div>
					<div class="carousel-item">
						<img src="@Model.ImageUrl" alt="Third slide">
					</div>
				</div>
				<ol class="carousel-indicators">
					<li data-target="#demoCarousel" data-slide-to="0" class="active"></li>
					<li data-target="#demoCarousel" data-slide-to="1"></li>
					<li data-target="#demoCarousel" data-slide-to="2"></li>
				</ol>
			</div>
		</div>

		<!-- Right Column -->
		<div class="col">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
					<li class="breadcrumb-item"><a href="@Url.Action("Index","Storefront")">Products</a></li>
					<li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
				</ol>
			</nav>
			<h5>SKU <span class="sku-holder">@Model.Id</span></h5>
			<h2>@Model.Name</h2>
			<h4>@Model.Price.ToString("C", new CultureInfo("en-US"))</h4>
			<form method="get" action="@Url.Action("Personalize", "Storefront")">
				<div class="form-group">
					<label for="quantity-group">Quantity</label>
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text"><div class="minus"></div></div>
						</div>
						<input type="text" class="form-control" id="quantity-group" value="1" disabled>
						<div class="input-group-append">
							<div class="input-group-text"><div class="plus"></div></div>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="option-1">Option 1</label>
					<select class="form-control" id="option-1" area-placeholder="Choose an option" disabled>
						<option>Choose an option</option>
						<option>Value 1</option>
						<option>Value 2</option>
					</select>
				</div>
				<input type="hidden" value="@Model.Id" name="id" />
				<button type="submit" class="btn btn-primary btn-lg">Personalize</button>
				<div class="form-group">
					<label for="LoadDataToTemplate">Load data from a server to a template</label>
					<input type="checkbox" data-val="true" id="LoadDataToTemplate" name="LoadDataToTemplate" value="true">
				</div>
			</form>
			<div class="card m-1">
				<div class="card-body">
					<h5 class="card-title">Description</h5>
					<p class="card-text">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
						Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
						dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
						non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

Views/Storefront/Index.cshtml
@model IEnumerable<Product>;
@using System.Globalization;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewData["Title"] = "Storefront";
}
<div class="container">
	<h1>@ViewData["Title"]</h1>
    <p class="lead">
        This page represents your storefront. It displays products from your ecommerce system (some stub objects in this sample app). If a product is "connected" to a Customer's Canvas product specification, you will be able to edit it.
    </p>
	@if (Model.Count() == 0) {
		<p class="alert alert-danger">You haven't connected any products. Go to Product → Link and create your first Product Link</p>
	}
	<div class="row">
		@foreach (var product in Model)
		{
			<div class="col-4">
				<img class="card-img-top" src="@product.ImageUrl" alt="@product.Name">
				<div class="card">
					<div class="card-body">
						<div class="card-title">
							<h5 class="card-title">@product.Name</h5>
							<p class="card-text">@product.Price.ToString("C", new CultureInfo("en-US", false))</p>
							<a href="@Url.Action("Edit", "Storefront", new { id = product.Id } )" class="btn btn-primary">Open product</a>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

Views/Storefront/Personalize.cshtml
@model Product
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@section Scripts {
	<script src="https://staticjs-aurigma.azureedge.net/back-office/storefront/1.2.7/storefront.main.js"></script>

	<script type="module">
		document.addEventListener("DOMContentLoaded", async function (event) {
			const backoffice = new Aurigma.BackOffice({
				tenantId: @ViewBag.TenantId,
				backOfficeUrl: "@ViewBag.BackOfficeUrl",
				pluginSettings: { currency: 'USD' }
			});

			const userInfo = {id: "@ViewBag.UserId" };
			
			let loadDataToTemplate = @ViewBag.LoadDataToTemplate.ToString().ToLower();
			if (loadDataToTemplate == true) {
				
				// Here you can loaad predefined information in template
				userInfo.data = @Json.Serialize(ViewBag.Data);
			}

			const container = document.getElementById('editor-container');

			const data = await backoffice.templates.findByProduct(@Model.Id);
			await backoffice.loadEditor(container, data, userInfo);

			backoffice.onFinish.subscribe(async (backoffice, project) => {
				// It is supposed that this code is called from a Shopping Cart, but for 
				// simplicity, we do it immediately. As a part of the Project Data you need
				// to send an Order ID which is normally known by the time when you checkout
				// (and complete the order). For this example, we will just hardcode it.
				const orderId = "12345678";

				debugger;
				const projectRequest = await fetch("@Url.Action("Create", "Projects")", {
					method: "post",
					headers: {
						"Content-Type": "application/json"
					},
					body: JSON.stringify({
						items: project.line_items,
						productId: "@Model.Id",
						userId: userInfo.id,
						orderId: orderId,
						ownerId: userInfo.id
					})
				});
				const savedProject = await projectRequest.json();
				alert(`Project #${savedProject.id} was saved successfully. Go to Customer\'s Canvas Hub and it navigate to Projects. Then you can go to Jobs to find the output file`);
				window.location = "@Url.Action("Index", "Storefront")";
			});
		});
	</script>
}
<div id="editor-container" style="height:80vh;"></div>

Views/Storefront/SimpleEditor.cshtml
@model Product

@section Scripts {

	<script type="module">

		document.addEventListener("DOMContentLoaded", async function (event) {

			const simpleEditor = document.getElementsByTagName("au-simple-editor").item(0);

			simpleEditor.setEditorConfig({
				backOfficeUrl: "@ViewBag.BackOfficeUrl",
				tenantId: @ViewBag.TenantId,
				product: { id: @Model.Id },
				user: { id: "@ViewBag.UserId" },
				ecommerceSystemId: @ViewBag.EcommerceSystemId
			});

			simpleEditor.addEventListener("addtocart", async (e) => {
				// It is supposed that this code is called from a Shopping Cart, but for
				// simplicity, we do it immediately. As a part of the Project Data you need
				// to send an Order ID which is normally known by the time when you checkout
				// (and complete the order). For this example, we will just hardcode it.
				const orderId = "12345678";

				const lineItems = [
					{
						stateId: [
							e.detail.key
						],
						fields: {},
						hidden: {}
					}
				];
				const projectRequest = await fetch("@Url.Action("Create", "Projects")", {
					method: "post",
					headers: {
						"Content-Type": "application/json"
					},
					body: JSON.stringify({
						items: lineItems,
						productId: "@Model.Id",
						userId: "@ViewBag.UserId",
						orderId: orderId,
						ownerId: "@ViewBag.UserId"
					})
				});
				const savedProject = await projectRequest.json();
				alert(`Project #${savedProject.id} was saved successfully. Go to Customer\'s Canvas Hub and it navigate to Projects. Then you can go to Jobs to find the output file`);
				window.location = "@Url.Action("Index", "Storefront")";
			});

		});

	</script>

	<script src="https://staticjs-aurigma.azureedge.net/simple-editor/stable/editor.js"></script>
}

<link rel="stylesheet" href="https://staticjs-aurigma.azureedge.net/simple-editor/stable/styles.css">

<au-simple-editor></au-simple-editor>