Controllers/AdminController.cs
using CustomersCanvasSample.Models;
using CustomersCanvasSample.Services;
using CustomersCanvasSampleMVC.Enums;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CustomersCanvasSample.Controllers
{
    public class AdminController : Controller
    {
        private readonly EcommerceDataService _ecommerceDataService;

        public AdminController(
            EcommerceDataService ecommerceDataService)
        {
            _ecommerceDataService = ecommerceDataService;
        }

        public async Task<IActionResult> Index()
        {
            return View(new AdminModel()
            {
                Products = _ecommerceDataService.GetProducts(),
                ConnectedProducts = await _ecommerceDataService.GetConnectedProducts(),
                ConnectedPimProducts = await _ecommerceDataService.GetConnectedPimProducts()
            });
        }

        public async Task<IActionResult> Edit(string id)
        {
            return View(await _ecommerceDataService.GetProductData(id));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductDetails(string id, string name, float price)
        {
            _ecommerceDataService.UpdateProductDetails(id, name, price);

            return View("Edit", await _ecommerceDataService.GetProductData(id));
        }

        [HttpPost]
        public async Task<IActionResult> ConnectProduct(string productId, int productSpecificationId)
        {
            await _ecommerceDataService.ConnectProduct(productId, productSpecificationId);

            return View("Edit", await _ecommerceDataService.GetProductData(productId));
        }

        [HttpPost]
        public async Task<IActionResult> DisconnectProduct(string productId)
        {
            await _ecommerceDataService.DisconnectProduct(productId);

            return View("Edit", await _ecommerceDataService.GetProductData(productId));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateIntegrationDetails(string productId, string productEditorType)
        {
            _ecommerceDataService.UpdateEditorType(productId, Enum.Parse<EditorType>(productEditorType));

            return View("Edit", await _ecommerceDataService.GetProductData(productId));
        }
    }
}

Controllers/DesignsController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Aurigma.AssetProcessor;
using Aurigma.AssetStorage;
using CustomersCanvasSample.Models;
using CustomersCanvasSample.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace CustomersCanvasSample.Controllers
{
    public class DesignsController : Controller
    {
        private readonly IDesignsApiClient _designsApiClient;
        private readonly IDesignProcessorApiClient _designProcessorApiClient;
        private readonly CustomersCanvasOptions _options;

        private const string _path = "/";

        public DesignsController(
            IDesignsApiClient designsApiClient,
            IDesignProcessorApiClient designProcessorApiClient,
            IOptions<CustomersCanvasOptions> customersCanvasOptions)
        {
            _designsApiClient = designsApiClient;
            _designProcessorApiClient = designProcessorApiClient;
            _options = customersCanvasOptions.Value;
        }

        public async Task<IActionResult> Index()
        {
            var path = _path;
            var folder = await _designsApiClient.GetFolderAsync(path);

            return View(new DesignsFolderModel(path, folder));
        }

        [HttpPost]
        public async Task<ActionResult> UploadDesign(IFormFile design)
        {
            using var openReadStream = design.OpenReadStream();
            var fileParameter = new Aurigma.AssetProcessor.FileParameter(openReadStream, design.FileName);

            await _designProcessorApiClient.ImportDesignAsync(sourceFile: fileParameter);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(string id, string name)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.DesignEditorVersion = _options.DesignEditorVersion;

            return View(new DesignModel(id, name));
        }

        public IActionResult EditWithUIF(string id, string name, string configName)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.DesignEditorVersion = _options.DesignEditorVersion;

            using var uiFrameworkConfigService = UIFrameworkService.FromAppData(
                Path.Combine(
                    AppDomain.CurrentDomain.GetData("DataDirectory").ToString(),
                    "ui-framework",
                    configName
                ));

            return View(new DesignModel(
                id,
                name,
                uiFrameworkConfigService.GetConfigAsJsonString(true)));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StorefrontController.cs
using CustomersCanvasSample.Services;
using CustomersCanvasSampleMVC.Enums;
using CustomersCanvasSampleMVC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomersCanvasSample.Controllers
{
    public class StorefrontController : Controller
    {
        private EcommerceDataService _ecommerceDataService;
        private readonly DataSourceService _dataSourceService;
        private CustomersCanvasOptions _options;

        public StorefrontController(
            EcommerceDataService ecommerceDataService,
            DataSourceService dataSourceService,
            IOptions<CustomersCanvasOptions> options)
        {
            _ecommerceDataService = ecommerceDataService;
            _dataSourceService = dataSourceService;
            _options = options.Value;
        }

        public async Task<IActionResult> Index()
        {
            var connectedProducts = await _ecommerceDataService.GetConnectedProducts();
            var connectedPimProducts = await _ecommerceDataService.GetConnectedPimProducts();

            return View(connectedProducts.Union(connectedPimProducts));
        }

        public IActionResult Edit(string id)
        {
            var product = _ecommerceDataService.GetProductById(id);

            ViewBag.TenantId = _options.TenantId;
            ViewBag.BackOfficeUrl = _options.IdentityProviderUrl;
            ViewBag.EcommerceSystemId = _options.StorefrontId;

            // It is supposed that user is authorised.
            // Otherwise the session should be generated.
            ViewBag.UserId = 1234;

            return product.EditorType switch
            {
                EditorType.UIFramework => View(product),
                EditorType.SimpleEditor => View("SimpleEditor", product),
                _ => throw new NotImplementedException(),
            };
        }

        public IActionResult Personalize(string id, bool LoadDataToTemplate)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.BackOfficeUrl = _options.IdentityProviderUrl;
            ViewBag.LoadDataToTemplate = LoadDataToTemplate;

            // It is supposed that user is authorised.
            // Otherwise the session should be generated.
            ViewBag.UserId = 1234;
            ViewBag.Data = _dataSourceService.GetDataForTemplate();

            return View(_ecommerceDataService.GetProductById(id));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Customer's Canvas - ASP.NET MVC Demo</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
	@RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/cc-logo.svg" alt="Customer's Canvas"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<div class="lead">Demo 1</div>
                                <span class="text-muted small">StorefrontJS Integration</span>
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
								<a class="nav-link text-dark" asp-area="" asp-controller="Storefront" asp-action="Index">Storefront</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Designs" asp-action="Index">
								<div class="lead">Demo 2</div>
								<span class="text-muted small">UIF + E-comm driver Integration (Legacy)</span>
							</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Aurigma, Inc. <a href="https://customerscanvas.com">Learn more</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>