Controllers/DesignPreviewController.cs
using System.IO;
using System.Threading.Tasks;
using Aurigma.AssetProcessor;
using Microsoft.AspNetCore.Mvc;

namespace CustomersCanvasSample.Controllers
{
    public class DesignPreviewController : Controller
    {
        private readonly IDesignProcessorApiClient _designProcessorApiClient;

        public DesignPreviewController(IDesignProcessorApiClient designProcessorApiClient)
        {
            _designProcessorApiClient = designProcessorApiClient;
        }

        public async Task<Stream> Index(string id, int? surfaceIndex)
        {
            const string previewNamespace = "demoapp";
            const string previewName = "thumbnail";
            const int previewWidth = 600;
            const int previewHeight = 600;

            var previewBody = await _designProcessorApiClient.PreparePreviewAsync(
                id,
                previewNamespace,
                previewName,
                previewWidth,
                previewHeight,
                surfaceIndex: surfaceIndex,
                force: true, // slower, but show all surfaces
                //stub: true, // faster, but don't work with multi surface states
                format: DesignPreviewFormat.Jpeg);

            return previewBody.Stream;
        }
    }
}

Controllers/DesignsController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Aurigma.AssetProcessor;
using Aurigma.AssetStorage;
using CustomersCanvasSample.Models;
using CustomersCanvasSample.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace CustomersCanvasSample.Controllers
{
    public class DesignsController : Controller
    {
        private readonly IDesignsApiClient _designsApiClient;
        private readonly IDesignProcessorApiClient _designProcessorApiClient;
        private readonly CustomersCanvasOptions _options;

        private const string _path = "/";

        public DesignsController(
            IDesignsApiClient designsApiClient,
            IDesignProcessorApiClient designProcessorApiClient,
            IOptions<CustomersCanvasOptions> customersCanvasOptions)
        {
            _designsApiClient = designsApiClient;
            _designProcessorApiClient = designProcessorApiClient;
            _options = customersCanvasOptions.Value;
        }

        public async Task<IActionResult> Index()
        {
            var path = _path;
            var folder = await _designsApiClient.GetFolderAsync(path);

            return View(new DesignsFolderModel(path, folder));
        }

        [HttpPost]
        public async Task<ActionResult> UploadDesign(IFormFile design)
        {
            using var openReadStream = design.OpenReadStream();
            var fileParameter = new Aurigma.AssetProcessor.FileParameter(openReadStream, design.FileName);

            await _designProcessorApiClient.ImportDesignAsync(sourceFile: fileParameter);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(string id, string name)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.DesignEditorVersion = _options.DesignEditorVersion;

            return View(new DesignModel(id, name));
        }

        public IActionResult EditWithUIF(string id, string name, string configName)
        {
            ViewBag.TenantId = _options.TenantId;
            ViewBag.DesignEditorVersion = _options.DesignEditorVersion;

            using var uiFrameworkConfigService = UIFrameworkService.FromAppData(
                Path.Combine(
                    AppDomain.CurrentDomain.GetData("DataDirectory").ToString(),
                    "ui-framework",
                    configName
                ));

            return View(new DesignModel(
                id,
                name,
                uiFrameworkConfigService.GetConfigAsJsonString(true)));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Designs/DesignEdit.cshtml
@model DesignModel

@section Styles {
	<link href="@Url.Content("~/css/editor-page.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
	<!-- INSERT CUSTOMER'S CANVAS URL HERE!-->
	<!-- To the base URL of your CC instance add /Resources/Generated/IframeApi.js -->
	<script type="text/javascript" id="CcIframeApiScript" src="https://cc-apps.aurigma.net/@ViewBag.TenantId/design-editor/@ViewBag.DesignEditorVersion/Resources/Generated/IframeApi.js"></script><!-- -->
}
@{
	ViewData["Title"] = "Edit " + Model.Name;
}
<div class="container">
	<nav class="navbar navbar-light bg-light">
		<ul class="nav">
			<li class="nav-item">
				<button id="download" disabled class="btn btn-primary">Download Result</button>
			</li>
		</ul>
	</nav>
	<div class="row">
		<div class="col">
			<div class="main__iframe">
				<iframe id="editorFrame"></iframe>
			</div>
			<div class="main__section main__section-version">
				<div class="main__version" id="version-box">
					ver.
				</div>
			</div>
		</div>
	</div>
</div>
<script>

	// A helper function to download the URL
	// https://stackoverflow.com/a/49917066/4173445
	function download(url) {
		let link = document.createElement("a");
		link.style = "position:absolute; top:-99999999; left:-9999999; visibility:hidden";
		link.href = url;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
	};


	document.addEventListener('DOMContentLoaded', async () => {

		const config = {
			userId: 123,
			canvas: {
				canvasItemHoverEnabled: true,
				containerColor: "#eee",
				shadowEnabled: true,
				ruler: {
					enabled: false
				}
			},
			fontList: {
				appFonts: ["*"]
			},
			assetSources: {
				"My files": {
					type: "PrivateSource",
					allowedExtensions: [
						"jpg",
						"jpeg",
						"png",
						"pdf",
						"bmp",
						"tif",
						"tiff",
						"svg"
					]
				},
				"Images": {
					type: "PublicSource",
					rootCategory: {
						name: ""
					},
					actionMode: {
						"psd": "Design",
						"svg": "Clipart",
						"pdf": "Vector",
						"ai": "Vector"
					}
				},
				"Background": {
					type: "PublicSource",
					rootFolder: {
						"show": true
					},
					rootCategory: {
						name: "Background"
					},
					actionMode: {
						"psd": "Merged",
						"svg": "Vector",
						"pdf": "Vector",
						"ai": "Vector"
					}
				}
			},
			widgets: {
				AssetManager: {
					tabs: [{
						name: "My files",
						assetSourceInstance: "My files",
						iconClassName: "cc-icon-uploadable",
						controls: {
							toolbarEnabled: false
						}
					},
					{
						name: "Images",
						assetSourceInstance: "Images",
						iconClassName: "cc-icon-add-image",
						controls: {
							categoriesEnabled: true,
							assetNameEnabled: true,
							toolbarEnabled: true
						}
					},
					{
						name: "Background",
						assetSourceInstance: "Background",
						iconClassName: "cc-icon-background",
						controls: {
							categoriesEnabled: true,
							assetNameEnabled: true,
							toolbarEnabled: true
						}
					}]
				},
				Toolbox: {
					buttons: [
						"Text",
						{
							translationKey: "Toolbox.SHAPE",
							translationKeyTitle: "Toolbox.TITLE_ADD_SHAPE",
							iconClass: "cc-icon-add-shape",
							buttons: [
								"Line",
								"Rectangle",
								"Ellipse"
							]
						},
						"QrCode",
						{
							"action": "Image",
							"iconClass": "cc-icon-uploadable",
							"tabs": [
								"My files"
							]
						},
						{
							"action": "Image",
							"iconClass": "cc-icon-add-image",
							"tabs": [
								"Images"
							]
						},
						{
							"action": "Background",
							"iconClass": "cc-icon-background",
							"tabs": [
								"Background"
							]
						}
					]
				}
			},
			violationWarningsSettings: {
				qualityMeter: {
					enabled: false
				},
				regionViolationWarningEnabled: true,
				safetyLineViolationWarningEnabled: false,
				textCropViolationWarningEnabled: true,
				shapeViolationsEnabled: true
			},
			rendering: {
				hiResOutputDpi: 72,
				hiResOutputFileFormat: "png",
				hiResOutputColorSpace: "rgb",
				proofImageSafetyLinesEnabled: false
			}
		};

		document.getElementById("version-box").innerText = "version " + CustomersCanvas.VERSION;

		var editor = await CustomersCanvas.IframeApi.loadEditor(
					document.getElementById("editorFrame"), "@Model.Id", config);

		document.getElementById("download").removeAttribute("disabled");
		document.getElementById("download").addEventListener("click", async () => {
			const result = await editor.finishProductDesign({
				fileName: '@Model.Name',
				generateLargePreviews: true,
				pregeneratePreviewImages: true
			});
			result
				.hiResOutputUrls
				.forEach(download);
		});

	});
</script>

Views/Designs/DesignFolderView.cshtml
@model DesignBrowserMVC.Models.DesignsFolderModel

@{
	ViewData["Title"] = "Designs at " + Model.Path;
}

<h1>@ViewData["Title"]</h1>

<div class="container">
	<div class="card-columns">
		@foreach (var item in Model.Content.Entities)
		{
			var previewUrl = Url.Action("Index", "DesignPreview", new { id = item.Id });
			<div class="card" style="width: 18rem;">
				<img class="card-img-top" src="@previewUrl" alt="@item.Name">
				<div class="card-body">
					<h5 class="card-title">@item.Name</h5>
					<p class="card-text">Last modified: @item.LastModified.ToString("dd MMM yyyy")</p>
				</div>
				<div class="card-body">
					<a href="#" class="card-link">@Html.ActionLink("Edit", "Edit", new { id = item.Id, name = item.Name })</a>
				</div>
			</div>
		}
	</div>
</div>

Views/Designs/Edit.cshtml
@model DesignModel

@section Styles {
	<link href="@Url.Content("~/css/editor-page.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
	<!-- INSERT CUSTOMER'S CANVAS URL HERE!-->
	<!-- To the base URL of your CC instance add /Resources/Generated/IframeApi.js -->
	<script type="text/javascript" id="CcIframeApiScript" src="https://cc-apps.aurigma.net/@ViewBag.TenantId/design-editor/@ViewBag.DesignEditorVersion/Resources/Generated/IframeApi.js"></script><!-- -->
}
@{
	ViewData["Title"] = "Edit " + Model.Name;
}
<div class="container">
	<nav class="navbar navbar-light bg-light">
		<ul class="nav">
			<li class="nav-item">
				<button id="download" disabled class="btn btn-primary">Download Result</button>
			</li>
		</ul>
	</nav>
	<div class="row">
		<div class="col">
			<div class="main__iframe">
				<iframe id="editorFrame"></iframe>
			</div>
			<div class="main__section main__section-version">
				<div class="main__version" id="version-box">
					ver.
				</div>
			</div>
		</div>
	</div>
</div>
<script>

	document.addEventListener('DOMContentLoaded', async () => {

		const config = {
			userId: 123,
			canvas: {
				canvasItemHoverEnabled: true,
				containerColor: "#eee",
				shadowEnabled: true,
				ruler: {
					enabled: false
				}
			},
			fontList: {
				appFonts: ["*"]
			},
			assetSources: {
				"My files": {
					type: "PrivateSource",
					allowedExtensions: [
						"jpg",
						"jpeg",
						"png",
						"pdf",
						"bmp",
						"tif",
						"tiff",
						"svg"
					]
				},
				"Images": {
					type: "PublicSource",
					rootCategory: {
						name: ""
					},
					actionMode: {
						"psd": "Design",
						"svg": "Clipart",
						"pdf": "Vector",
						"ai": "Vector"
					}
				},
				"Background": {
					type: "PublicSource",
					rootFolder: {
						"show": true
					},
					rootCategory: {
						name: "Background"
					},
					actionMode: {
						"psd": "Merged",
						"svg": "Vector",
						"pdf": "Vector",
						"ai": "Vector"
					}
				}
			},
			widgets: {
				AssetManager: {
					tabs: [{
						name: "My files",
						assetSourceInstance: "My files",
						iconClassName: "cc-icon-uploadable",
						controls: {
							toolbarEnabled: false
						}
					},
					{
						name: "Images",
						assetSourceInstance: "Images",
						iconClassName: "cc-icon-add-image",
						controls: {
							categoriesEnabled: true,
							assetNameEnabled: true,
							toolbarEnabled: true
						}
					},
					{
						name: "Background",
						assetSourceInstance: "Background",
						iconClassName: "cc-icon-background",
						controls: {
							categoriesEnabled: true,
							assetNameEnabled: true,
							toolbarEnabled: true
						}
					}]
				},
				Toolbox: {
					buttons: [
						"Text",
						{
							translationKey: "Toolbox.SHAPE",
							translationKeyTitle: "Toolbox.TITLE_ADD_SHAPE",
							iconClass: "cc-icon-add-shape",
							buttons: [
								"Line",
								"Rectangle",
								"Ellipse"
							]
						},
						"QrCode",
						{
							"action": "Image",
							"iconClass": "cc-icon-uploadable",
							"tabs": [
								"My files"
							]
						},
						{
							"action": "Image",
							"iconClass": "cc-icon-add-image",
							"tabs": [
								"Images"
							]
						},
						{
							"action": "Background",
							"iconClass": "cc-icon-background",
							"tabs": [
								"Background"
							]
						}
					]
				}
			},
			violationWarningsSettings: {
				qualityMeter: {
					enabled: false
				},
				regionViolationWarningEnabled: true,
				safetyLineViolationWarningEnabled: false,
				textCropViolationWarningEnabled: true,
				shapeViolationsEnabled: true
			},
			rendering: {
				hiResOutputDpi: 72,
				hiResOutputFileFormat: "png",
				hiResOutputColorSpace: "rgb",
				proofImageSafetyLinesEnabled: false
			}
		};

		document.getElementById("version-box").innerText = "version " + CustomersCanvas.VERSION;

		var editor = await CustomersCanvas.IframeApi.loadEditor(
					document.getElementById("editorFrame"), "@Model.Id", config);

		document.getElementById("download").removeAttribute("disabled");
		document.getElementById("download").addEventListener("click", async () => {
			const result = await editor.finishProductDesign({
				fileName: '@Model.Name',
				generateLargePreviews: true,
				pregeneratePreviewImages: true
			});
			result
				.hiResOutputUrls
				.forEach(download); /* You may find download function in wwwroot/js/site.js */
		});

	});
</script>

Views/Designs/EditWithUIF.cshtml
@model DesignModel

@{
	ViewData["Title"] = "Edit " + Model.Name;

	var uiFrameworkVersion = "4.18.0";
	var uiFrameworkBaseUrl = "https://staticjs-aurigma.azureedge.net/ui-framework/" + uiFrameworkVersion;
}

@section Styles {
	<link href="@Url.Content("~/css/editor-page.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
	<!-- INSERT CUSTOMER'S CANVAS URL HERE!-->
	<!-- To the base URL of your CC instance add /Resources/Generated/IframeApi.js -->
	<script type="text/javascript" id="CcIframeApiScript" src="https://cc-apps.aurigma.net/@ViewBag.TenantId/design-editor/@ViewBag.DesignEditorVersion/Resources/Generated/IframeApi.js"></script><!-- -->
}

<div class="container">
	<div class="row">
		<div class="col">
			<div class="editor-parent" id="editor-parent"></div>
		</div>
	</div>
</div>
<script type="module">
	import moduleLoader from "@uiFrameworkBaseUrl/moduleLoader.js";

	document.addEventListener('DOMContentLoaded', async () => {

		// --- Initialize data from your application ---

		/*
		 * It is supposed that it reflects the product model from your application.
		 *
		 * The important part here is the attributes. It is supposed that you add a reference
		 * to a design to the product model in your admin panel. In this demo, for brevity,
		 * we pass an Id of a design clicked by a user.
		 * 
		 * The required attributes are listed in the config (e.g. see the App_Data/ui-framework/standard-editor.json)
		 */
		const productModel = {
			id: 0,
			sku: "TEST-0001234",
			title: "@Model.Name",
			description: "This is a test product",
			options: [],
			price: 19.99,
			attributes: [
				{
					id: 10001,
					title: "Design",
					value: {
						id: "@Model.Id"
					}
				},
				{
					id: 10002,
					title: "Clipart",
					value: {
						fullPath: "/"
					}
				},
				{
					id: 10003,
					title: "Output Resolution",
					value: 300
				},
				{
					id: 10004,
					title: "AdvancedModeOn",
					value: true
				}
			]
		}

		const quantity = 1;

		const userModel = {
			id: "1234567"
		}

		const config = @Html.Raw(Model.Config);

		const settings = { customersCanvasBaseUrl: "https://cc-apps.aurigma.net/@ViewBag.TenantId/design-editor/@ViewBag.DesignEditorVersion/" };

		// --- Load UI Framework scripts and pass data into it ---

		const driverModule = await moduleLoader.dynamicImport("ecommerceDriver", "@uiFrameworkBaseUrl/drivers/default-driver.js")
		const driver = driverModule.ecommerceDriver;

		const editorModule = await moduleLoader.dynamicImportDefault("editor", "@uiFrameworkBaseUrl/editor.js");
		const editor = editorModule.editor?.editor ?? editorModule.editor;  // depending on a UI Framework version, it may be inside a nested object.

		// Initialization - you should provide us with a product definition, editor instance,
		// config, data returned by the editor, items quantity (when it is necessary).
		const ecommerce = await driver.init(productModel, editor, config, settings, null, quantity, userModel);

		// Display the editor in the specified div element
		ecommerce.products.current.renderEditor(document.getElementById("editor-parent"));

		// Subscribe an event which will be called when the user finishes editing (you are supposed to put a code which
		// sends the product to a shopping cart).

		ecommerce.cart.onPriceChanged.subscribe(data => {
			console.log("onPriceChanged: price: " + data.price + ", priceLocalized: " + data.priceLocalized);
		});

		ecommerce.cart.onSubmitting.subscribe(data => console.log("submitting", data));
		ecommerce.cart.onSubmitted.subscribe(data => {
			// It contains the stateId, userId, preview images and the other output data.
			console.log("submitted");
			data.lineItems.forEach((order, index) => {
				console.log(`Line item ${index + 1}: Private Design ID = ${order.props._stateId.join(", ")} for the user ${order.props._userId}`);
			});
		});

	});
</script>

Views/Designs/Index.cshtml
@model CustomersCanvasSample.Models.DesignsFolderModel

@{ ViewData["Title"] = "Designs at " + Model.Path; }

<h1>@ViewData["Title"]</h1>

@section Scripts
{
    <script type="text/javascript">
        $(document)
            .ready(function () {
                $("#spinner").hide();

                $("#fileUpload").on("change",
                    function () {
                        var formFile = $("#designForm")[0];

                        $("#fileUpload").hide();
                        $("#spinner").show();

                        $.ajax({
                            url: 'Designs/UploadDesign',
                            type: 'POST',
                            data: new FormData(formFile),
                            cache: false,
                            contentType: false,
                            processData: false,
                            complete: function (response) {

                                $("#fileUpload").show();
                                $("#spinner").hide();

                                window.location.reload();
                            }
                        });
                    });
            });
    </script>
}

<div class="container">
    <div class="row mt-2">
        @using (Html.BeginForm("UploadDesign", "Designs", FormMethod.Post, new { @class = "form-inline", enctype = "multipart/form-data", @id = "designForm" }))
        {
            <div class="input-group" style="min-width: 400px;">
                <label class="col-md-4" for="fileUpload">Upload design</label>

                <div class="col-md-8">
                    <input type="file" class="form-control-file" id="fileUpload" name="design">
                    <img src="img/ininite-loop.gif" style="height: 30px" id="spinner">
                </div>
            </div>
        }
    </div>
    <div class="row mt-2">
        <div class="card-columns">
            @foreach (var item in Model.Content.Entities)
            {
                <div class="card" style="width: 18rem;">

                    <div class="card-header">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-subtitle mb-2 text-muted">Last modified: @item.LastModified.ToString("dd MMM yyyy")</p>
                    </div>

                    <div class="card-body">
                        <div id="surfaceCarousel_@item.Id" class="carousel slide" data-ride="carousel" data-interval="false">
                            <div class="carousel-inner">

                                @{ var surfacesArray = item.Metadata.Surfaces.ToArray(); }
                                @{
                                    for (var surfaceIndex = 0; surfaceIndex < surfacesArray.Length; ++surfaceIndex)
                                    {
                                        var s = surfacesArray[surfaceIndex];
                                        <div class="carousel-item @(@surfaceIndex == 0 ? "active" : "") ">
                                            <h6>Surface @(surfaceIndex + 1) / @surfacesArray.Length</h6>
                                            <img class="card-img-top" src="@Url.Action("Index", "DesignPreview", new {id = item.Id, surfaceIndex = @surfaceIndex})" alt="@surfaceIndex">
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">
                                                    <p class="card-text">Size: @((s.Height / 72).ToString("N2"))in x @((s.Width / 72).ToString("N2"))in</p>
                                                </li>
                                                <li class="list-group-item">
                                                    <a href="#" class="card-link">@Html.ActionLink("Background", "ExtractBackground", controllerName: "DesignAtomsApi", new { id = item.Id, surfaceIndex = @surfaceIndex })</a>
                                                </li>
                                            </ul>
                                        </div>
                                    }
                                }
                            </div>
                            @if (surfacesArray.Length > 1)
                            {
                                <a class="carousel-control-prev" href="#surfaceCarousel_@item.Id" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="false"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#surfaceCarousel_@item.Id" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="false"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            }
                        </div>
                    </div>
                    <div class="card-footer">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <a href="#" class="card-link">@Html.ActionLink("Open with IFrame API", "Edit", new { id = item.Id, name = item.Name })</a>
                            </li>
                            <li class="list-group-item">
                                <a href="#" class="card-link">@Html.ActionLink("Open with UI Framework", "EditWithUIF", new { id = item.Id, name = item.Name, configName = "standard-editor.json" })</a>
                            </li>
                        </ul>
                    </div>
                </div>
            }
        </div>
    </div>
</div>